package com.thatmg393.ts4j.world.moon;

public enum MoonStyles {
	WHITE_MOON,
	ORANGE_MOON,
	RINGED_GREEN_MOON,
	BLUE_MOON,
	ICE_MOON,
	GREEN_MOON,	
	PINK_MOON,
	PINK_ORANGE_MOON,
	TRIPLE_PURPLE_MOON
}
